services:
  app:
    build: ./app
    container_name: banking-sistem
    ports:
      - "3000:3000"
    volumes:
      - ./app/logs:/app/logs
      - ./app/public:/app/public
    environment:
      - SEED_USERNAME=teste
      - SEED_PASSWORD=teste123
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: banking-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: banking-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: banking-loki
    user: root
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
    command:
      - '-config.file=/etc/loki/loki-config.yml'
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: banking-promtail
    volumes:
      - ./app/logs:/app/logs
      - ./monitoring/promtail:/etc/promtail
    command:
      - '-config.file=/etc/promtail/promtail-config.yml'
    restart: unless-stopped
